USE QUANLYPHONGMACHTU

ALTER TABLE PHIEUKB
DROP CONSTRAINT FKBENHNHANPHIEUKB

ALTER TABLE PHIEUKB
DROP CONSTRAINT CHECKMABENHNHAN

ALTER TABLE PHIEUKB
DROP COLUMN MABENHNHAN

ALTER TABLE PHIEUKB
ADD MACTKB NVARCHAR(9) NOT NULL

ALTER TABLE PHIEUKB
ADD CONSTRAINT FKCTKB FOREIGN KEY (MACTKB) REFERENCES CTKB (MACTKB)

ALTER TABLE HOADON
DROP CONSTRAINT FKBENHNHANHD

ALTER TABLE HOADON
DROP CONSTRAINT CHECKMABENHNHANA

ALTER TABLE HOADON
DROP COLUMN MABENHNHAN

ALTER TABLE HOADON
ADD MACTKB NVARCHAR(9) NOT NULL

ALTER TABLE HOADON
ADD CONSTRAINT FKCTKBA FOREIGN KEY (MACTKB) REFERENCES CTKB (MACTKB)

ALTER TRIGGER TINHTONGTIENTHUOC ON HOADON
FOR INSERT
AS
	BEGIN
		UPDATE HOADON
		SET TONGTIENTHUOC = (
								SELECT SUM(TIENTHUOC)
								FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
								WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
									AND HOADON.MACTKB = CT.MACTKB
							)
	END

ALTER TRIGGER DIEUCHINHCTPHIEUKB ON CTPHIEUKB
FOR INSERT, UPDATE
AS
	BEGIN
		UPDATE HOADON
		SET TONGTIENTHUOC = (
								SELECT SUM(TIENTHUOC)
								FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
								WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
									AND HOADON.MACTKB = CT.MACTKB
							)
		WHERE MACTKB = (
								SELECT CT.MACTKB
								FROM INSERTED I, PHIEUKB P, CTKB CT
								WHERE I.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB
								UNION
								SELECT CT.MACTKB
								FROM DELETED D, PHIEUKB P, CTKB CT
								WHERE D.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB
							)
	END

ALTER TRIGGER TINHSOLUONGTHUOCSUDUNG ON SUDUNGTHUOC
FOR INSERT
AS
	BEGIN
		UPDATE SUDUNGTHUOC
		SET SOLUONGDUNG = (
								SELECT SUM(SOLUONG)
								FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
								WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
									AND SUDUNGTHUOC.MATHUOC = CTP.MATHUOC 
									AND SUDUNGTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
									AND SUDUNGTHUOC.NAM = YEAR(CT.NGAYKHAMBENH) 
						  )
	END

ALTER TRIGGER DIEUCHINHCTPHIEUKBA ON CTPHIEUKB
FOR INSERT
AS
	BEGIN
		UPDATE SUDUNGTHUOC
		SET SOLUONGDUNG = (
							    SELECT SUM(SOLUONG)
								FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
								WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
									AND SUDUNGTHUOC.MATHUOC = CTP.MATHUOC 
									AND SUDUNGTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
									AND SUDUNGTHUOC.NAM = YEAR(CT.NGAYKHAMBENH) 
						  )
		WHERE MATHUOC = (
							SELECT MATHUOC
							FROM INSERTED
						)
	END

ALTER TRIGGER DEMSOLANDUNG ON SUDUNGTHUOC
FOR INSERT
AS
	BEGIN
		UPDATE SUDUNGTHUOC
		SET SOLANDUNG = (
							SELECT COUNT(*)
							FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
							WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB
								AND SUDUNGTHUOC.MATHUOC = CTP.MATHUOC 
								AND SUDUNGTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
								AND SUDUNGTHUOC.NAM = YEAR(CT.NGAYKHAMBENH)
						)
	END
	
ALTER TRIGGER DIEUCHINHCTPHIEUKBB ON CTPHIEUKB
FOR INSERT
AS
	BEGIN
		UPDATE SUDUNGTHUOC
		SET SOLANDUNG = (
							SELECT COUNT(*)
							FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
							WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
								AND SUDUNGTHUOC.MATHUOC = CTP.MATHUOC 
								AND SUDUNGTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
								AND SUDUNGTHUOC.NAM = YEAR(CT.NGAYKHAMBENH)
						)
		WHERE MATHUOC = (
							SELECT MATHUOC
							FROM INSERTED
						)
	END
	
ALTER TRIGGER TINHDOANHTHU ON DOANHTHU
FOR INSERT
AS
	BEGIN
		UPDATE DOANHTHU
		SET DOANHTHU = (
						   SELECT SUM(TONGTIENTHUOC)
						   FROM HOADON HD, CTKB CT
						   WHERE HD.MACTKB = CT.MACTKB AND CT.NGAYKHAMBENH = DOANHTHU.NGAYLAP
					   )
	END

ALTER TRIGGER DIEUCHINHHOADON ON HOADON
FOR INSERT, UPDATE
AS
	BEGIN
		UPDATE DOANHTHU
		SET DOANHTHU = (
						   SELECT SUM(TONGTIENTHUOC)
						   FROM HOADON HD, CTKB CT
						   WHERE HD.MACTKB = CT.MACTKB AND CT.NGAYKHAMBENH = DOANHTHU.NGAYLAP
					   )
		WHERE NGAYLAP = (
							SELECT CT.NGAYKHAMBENH
							FROM INSERTED I, CTKB CT
							WHERE I.MACTKB = CT.MACTKB
							UNION
							SELECT CT.NGAYKHAMBENH
							FROM DELETED D, CTKB CT
							WHERE D.MACTKB = CT.MACTKB
						)
	END