USE QUANLYPHONGMACHTU
GO

ALTER TABLE CACHDUNG
DROP CONSTRAINT PRIMARYKEYCACHDUNG
GO

ALTER TABLE CACHDUNG
ALTER COLUMN TENCACHDUNG NVARCHAR(100) NOT NULL
GO

ALTER TABLE CACHDUNG
ADD CONSTRAINT PRIMARYKEYCACHDUNG UNIQUE (TENCACHDUNG)
GO

CREATE TRIGGER KIEMTRASOLUONGTON ON CTPHIEUKB
FOR INSERT
AS
	BEGIN
		IF ((
				SELECT I.SOLUONG
				FROM INSERTED I
			) > (
					SELECT T.SOLUONGTON
					FROM THUOC T, INSERTED I
					WHERE T.MATHUOC = I.MATHUOC))
			ROLLBACK TRAN
	END