USE QUANLYPHONGMACHTU

DROP TABLE DOANHTHU

CREATE TABLE CTBCDOANHTHU
(
	MACTBCDOANHTHU NVARCHAR(7) PRIMARY KEY, 
	NGAYLAP SMALLDATETIME CHECK ((YEAR(NGAYLAP) < YEAR(GETDATE()) OR (YEAR(NGAYLAP) = YEAR(GETDATE()) 
		AND (MONTH(NGAYLAP) < MONTH(GETDATE())))) AND NGAYLAP IS NOT NULL), 
	SOBENHNHAN INT, 
	DOANHTHU INT, 
	TYLEDOANHTHUTHANG INT, 
	CONSTRAINT PRIMARYKEYCTBCDOANHTHU UNIQUE (NGAYLAP)
)

DROP TABLE SUDUNGTHUOC

CREATE TABLE CTBCSDTHUOC
(
	MACTBCSDTHUOC NVARCHAR(8) PRIMARY KEY, 
	THANG INT CHECK (THANG >= 1 AND THANG <= 12 AND THANG IS NOT NULL), 
	NAM INT NOT NULL, 
	MATHUOC NVARCHAR(6) NOT NULL, 
	SOLUONGDUNG INT, 
	SOLANDUNG INT, 
	CONSTRAINT PRIMARYKEYCTBCSDTHUOC UNIQUE (THANG, NAM, MATHUOC), 
	CONSTRAINT THANGNAM CHECK (NAM < YEAR(GETDATE()) OR (NAM = YEAR(GETDATE()) AND 
		THANG < MONTH(GETDATE()))), 
	CONSTRAINT FKTHUOC FOREIGN KEY (MATHUOC) REFERENCES THUOC (MATHUOC)
)

CREATE TRIGGER DEMSOBENHNHAN ON CTBCDOANHTHU
FOR INSERT
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET SOBENHNHAN = (
							 SELECT COUNT(*)
							 FROM BENHNHAN BN, CTKB CT
							 WHERE BN.MABENHNHAN = CT.MABENHNHAN 
								AND CTBCDOANHTHU.NGAYLAP = CT.NGAYKHAMBENH 
						 )
	END
	
DROP TRIGGER THEMBENHNHAN

CREATE TRIGGER THEMBENHNHAN ON BENHNHAN
FOR INSERT
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET SOBENHNHAN = (
							 SELECT COUNT(*)
							 FROM BENHNHAN BN, CTKB CT
							 WHERE BN.MABENHNHAN = CT.MABENHNHAN 
								AND CTBCDOANHTHU.NGAYLAP = CT.NGAYKHAMBENH 
						 )
		WHERE NGAYLAP = (
							SELECT CT.NGAYKHAMBENH
							FROM INSERTED I, CTKB CT
							WHERE I.MABENHNHAN = CT.MABENHNHAN
						)
	END
	
CREATE TRIGGER TINHDOANHTHU ON CTBCDOANHTHU
FOR INSERT
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET DOANHTHU = (
						   SELECT SUM(HD.TONGTIENTHUOC)
						   FROM HOADON HD, CTKB CT
						   WHERE HD.MACTKB = CT.MACTKB AND CT.NGAYKHAMBENH = CTBCDOANHTHU.NGAYLAP
					   )
	END
	
DROP TRIGGER DIEUCHINHHOADON

CREATE TRIGGER DIEUCHINHHOADON ON HOADON
FOR INSERT, UPDATE
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET DOANHTHU = (
						   SELECT SUM(HD.TONGTIENTHUOC)
						   FROM HOADON HD, CTKB CT
						   WHERE HD.MACTKB = CT.MACTKB AND CT.NGAYKHAMBENH = CTBCDOANHTHU.NGAYLAP
					   )
		WHERE NGAYLAP = (
							SELECT CT.NGAYKHAMBENH
							FROM INSERTED I, CTKB CT
							WHERE I.MACTKB = CT.MACTKB
							UNION
							SELECT CT.NGAYKHAMBENH
							FROM DELETED D, CTKB CT
							WHERE D.MACTKB = CT.MACTKB
						)
	END
	
CREATE TRIGGER TINHTYLEDOANHTHU ON CTBCDOANHTHU
FOR INSERT, UPDATE
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET TYLEDOANHTHUTHANG = DOANHTHU * 100 / (
													 SELECT SUM(CT.DOANHTHU)
													 FROM CTBCDOANHTHU CT
													 WHERE MONTH(CT.NGAYLAP) = 
														MONTH(CTBCDOANHTHU.NGAYLAP)
												 )
	END
	
CREATE TRIGGER TINHSOLUONGTHUOCSUDUNG ON CTBCSDTHUOC
FOR INSERT
AS
	BEGIN
		UPDATE CTBCSDTHUOC
		SET SOLUONGDUNG = (
								SELECT SUM(CTP.SOLUONG)
								FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
								WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
									AND CTBCSDTHUOC.MATHUOC = CTP.MATHUOC 
									AND CTBCSDTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
									AND CTBCSDTHUOC.NAM = YEAR(CT.NGAYKHAMBENH) 
						  )
	END
	
DROP TRIGGER DIEUCHINHCTPHIEUKBA

CREATE TRIGGER DIEUCHINHCTPHIEUKBA ON CTPHIEUKB
FOR INSERT
AS
	BEGIN
		UPDATE CTBCSDTHUOC
		SET SOLUONGDUNG = (
							    SELECT SUM(CTP.SOLUONG)
								FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
								WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
									AND CTBCSDTHUOC.MATHUOC = CTP.MATHUOC 
									AND CTBCSDTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
									AND CTBCSDTHUOC.NAM = YEAR(CT.NGAYKHAMBENH) 
						  )
		WHERE MATHUOC = (
							SELECT MATHUOC
							FROM INSERTED
						)
	END
	
CREATE TRIGGER DEMSOLANDUNG ON CTBCSDTHUOC
FOR INSERT
AS
	BEGIN
		UPDATE CTBCSDTHUOC
		SET SOLANDUNG = (
							SELECT COUNT(*)
							FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
							WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB
								AND CTBCSDTHUOC.MATHUOC = CTP.MATHUOC 
								AND CTBCSDTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
								AND CTBCSDTHUOC.NAM = YEAR(CT.NGAYKHAMBENH)
						)
	END
	
DROP TRIGGER DIEUCHINHCTPHIEUKBB

CREATE TRIGGER DIEUCHINHCTPHIEUKBB ON CTPHIEUKB
FOR INSERT
AS
	BEGIN
		UPDATE CTBCSDTHUOC
		SET SOLANDUNG = (
							SELECT COUNT(*)
							FROM CTPHIEUKB CTP, PHIEUKB P, CTKB CT
							WHERE CTP.MAPHIEUKB = P.MAPHIEUKB AND P.MACTKB = CT.MACTKB 
								AND CTBCSDTHUOC.MATHUOC = CTP.MATHUOC 
								AND CTBCSDTHUOC.THANG = MONTH(CT.NGAYKHAMBENH) 
								AND CTBCSDTHUOC.NAM = YEAR(CT.NGAYKHAMBENH)
						)
		WHERE MATHUOC = (
							SELECT MATHUOC
							FROM INSERTED
						)
	END

ALTER TRIGGER TINHTIENKHAM ON HOADON
FOR INSERT
AS
	BEGIN
		UPDATE HOADON
		SET TIENKHAM = (
						   SELECT GIATRI
						   FROM THAMSO
						   WHERE TENTHAMSO = N'Tiền khám'
					   )
	END

ALTER TABLE BENHNHAN
DROP CONSTRAINT CHECKGIOITINH

ALTER TABLE BENHNHAN
ADD CONSTRAINT CHECKGIOITINH CHECK ((GIOITINH = N'Nam' OR GIOITINH = N'Nữ' OR GIOITINH = N'Khác') 
	AND GIOITINH IS NOT NULL)

ALTER TRIGGER TINHDOANHTHU ON CTBCDOANHTHU
FOR INSERT
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET DOANHTHU = (
						   SELECT SUM(HD.TONGTIEN)
						   FROM HOADON HD, CTKB CT
						   WHERE HD.MACTKB = CT.MACTKB AND CT.NGAYKHAMBENH = CTBCDOANHTHU.NGAYLAP
					   )
	END
	
ALTER TRIGGER DIEUCHINHHOADON ON HOADON
FOR INSERT, UPDATE
AS
	BEGIN
		UPDATE CTBCDOANHTHU
		SET DOANHTHU = (
						   SELECT SUM(HD.TONGTIEN)
						   FROM HOADON HD, CTKB CT
						   WHERE HD.MACTKB = CT.MACTKB AND CT.NGAYKHAMBENH = CTBCDOANHTHU.NGAYLAP
					   )
		WHERE NGAYLAP = (
							SELECT CT.NGAYKHAMBENH
							FROM INSERTED I, CTKB CT
							WHERE I.MACTKB = CT.MACTKB
							UNION
							SELECT CT.NGAYKHAMBENH
							FROM DELETED D, CTKB CT
							WHERE D.MACTKB = CT.MACTKB
						)
	END

ALTER TABLE CTPHIEUNT
DROP CONSTRAINT CK__CTPHIEUNT__NGAYN__0B91BA14

ALTER TABLE CTPHIEUNT
ADD CONSTRAINT CHECKNGAYLAP CHECK (NGAYNHAPTHUOC >= CAST(GETDATE() AS DATE) 
	AND NGAYNHAPTHUOC IS NOT NULL)
		
ALTER TRIGGER TINHDONGIABANHIENTAI ON CTPHIEUNT
FOR INSERT
AS
	BEGIN
		UPDATE CTPHIEUNT
		SET DONGIABANHIENTAI = (
								   SELECT T.DONGIABAN
								   FROM THUOC T
								   WHERE T.MATHUOC = CTPHIEUNT.MATHUOC
							   )
		WHERE MACTPHIEUNT = (
								SELECT I.MACTPHIEUNT
								FROM INSERTED I
							)
	END

ALTER TRIGGER TINHTYLEDONGIABANHIENTAI ON CTPHIEUNT
FOR INSERT
AS
	BEGIN
		UPDATE CTPHIEUNT
		SET TYLETINHDONGIABANHIENTAI = (
								   SELECT T.TYLETINHDONGIABAN
								   FROM THUOC T
								   WHERE T.MATHUOC = CTPHIEUNT.MATHUOC
							   )
		WHERE MACTPHIEUNT = (
								SELECT I.MACTPHIEUNT
								FROM INSERTED I
							)
	END

ALTER TABLE CTKB
DROP CONSTRAINT CK__CTKB__NGAYKHAMBE__06CD04F7

ALTER TABLE CTKB
ADD CONSTRAINT CHECKNGAYKHAMBENHA CHECK (NGAYKHAMBENH >= CAST(GETDATE() AS DATE) AND 
	NGAYKHAMBENH IS NOT NULL)

ALTER TABLE CTBCSDTHUOC
DROP CONSTRAINT THANGNAM

ALTER TABLE CTBCSDTHUOC
ADD CONSTRAINT THANGNAM CHECK (NAM > 0 AND (NAM < YEAR(GETDATE()) OR (NAM = YEAR(GETDATE()) AND 
		THANG < MONTH(GETDATE()))))